pipeline:
  name: Azure-Terraform-Pipeline
  identifier: AzureTerraformPipeline
  projectIdentifier: Azure_Terraform_Demo
  orgIdentifier: default

  properties:
    ci:
      codebase:
        connectorRef: GitHubwTerraform_Connector
        repoName: tf_harnes_azure_pip
        build:
          type: branch
          spec:
            branch: main

  stages:
    - stage:
        name: Terraform
        identifier: Terraform
        type: Custom
        spec:
          execution:
            steps:

              - step:
                  type: TerraformPlan
                  name: Terraform_Plan
                  identifier: Terraform_Plan
                  spec:
                    provisionerIdentifier: azure_terraform
                    configuration:
                      command: apply
                      configFiles:
                        store:
                          type: Github
                          spec:
                            connectorRef: GitHubwTerraform_Connector
                            repoName: tf_harnes_azure_pip
                            gitFetchType: Branch
                            branch: main
                            folderPath: /
                      providerCredential:
                        type: Azure
                        spec:
                          connectorRef: Azure_Terraform_Connector
                          subscriptionId: e539ab70-9167-4979-b61b-c9eab7622d18

              - step:
                  type: HarnessApproval
                  name: Terraform_Approval
                  identifier: Terraform_Approval
                  spec:
                    approvers:
                      userGroups:
                        - <YOUR_USER_GROUP_IDENTIFIER>
                      minimumCount: 1
                      disallowPipelineExecutor: false

              - step:
                  type: TerraformApply
                  name: Terraform_Apply
                  identifier: Terraform_Apply
                  spec:
                    provisionerIdentifier: azure_terraform
                    configuration:
                      type: InheritFromPlan
